<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Classi Ofertas</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<link rel="stylesheet" type="text/css" href="css/style.css">
	</head>

	<body>

      <!-- DESKTOP VERSION -->
      <div id="desktop-version">

      	<!-- Cabeclaho -->
            <header id="cabecalho">

                    <!-- Login Pop Up -->
                    <div id="login-pop-up">

                        <div id="form-pop-up" class="responsive">
                            <div id="pop-up-campos">
                                
                                <div id="area-cadastrado">
                                   <p class="cadastrado-title">Já é cadastrado?</p>
                                   <input type="text" name="razaosocial" class="cadastrado" placeholder="Razão social:">
                                   <input type="text" name="nomefantasia" class="cadastrado" placeholder="Nome fantasia:">
                                   <input type="text" name="cnpj" class="cadastrado" placeholder="CNPJ:">
                                   <input type="email" name="emailcad" class="cadastrado" placeholder="E-mail:">
                                   <a href="#" class="btn-cadastrado">Entrar</a>
                                </div>

                                <div id="area-primera-vez">
                                    <p class="area-primera-vez-title">Primeira vez aqui?</p>
                                    <a href="#" class="btn-area-primera-vez">Fazer Cadastro</a>
                                </div>

                            </div>
                        </div>

                    </div>
                    <!-- Fim Login Pop Up -->

             	  <nav id="menu">
             	  	<div id="trace"></div><br>
             	  	<div id="trace"></div><br>
             	  	<div id="trace"></div>
             	  </nav>

                    <!-- Menu depois de clicado -->
                    <nav id="menu-after">
                        <ul>
                           <li><a href="#" class="sub-menu">Todas as Ofertas</a></li>
                           <li><a href="#" class="sub-menu">Ofertas em sua cidade</a></li>
                           <li><a href="#" class="sub-menu">Categorias</a></li>
                           <li><a href="#" class="sub-menu">Como funciona</a></li>
                           <li><a href="#" class="sub-menu">Quero anunciar</a></li>
                           <li><a href="#" class="sub-menu">Tire suas dúvidas</a></li>
                           <li><a href="#" class="sub-menu">Contato</a></li>
                        </ul>
                    </nav>

                    <nav id="sub-menu">
                        <ul>
                           <li><a href="#">Link 1</a></li>
                           <li><a href="#">Link 2</a></li>
                           <li><a href="#">Link 3</a></li>
                        </ul>
                    </nav>

             	  <figure id="logo">
      	       	 <img src="img/logo.png" class="logo">
      	        </figure>

             	  <div id="cabecalho" class="responsive">
                    
                <div id="search">
      		       <input type="text" name="procura" class="procura" placeholder="O que procura:">
      		       <input type="text" name="cidade" class="cidade" placeholder="Cidade:">
      		       <a href="#" class="btn-buscar-header">Buscar</a>
      		       <img src="img/cart.png" class="cart-icon">
      		       <a href="#" class="btn-login">Login</a>
      	        </div>

      	       	  <div id="banner-publicitario-1"></div>

             	  </div>

             	  <div id="slider">
             	  	<div id="arrow-left" class="next"></div>
             	  	<div id="arrow-right" class="prev"></div>
             	  	<div id="block-info"></div>

                           <div id="slider-1" class="slider-img"></div>
                           <div id="slider-2" class="slider-img"></div>
                           <div id="slider-3" class="slider-img"></div>
             	  </div>

             </header>
             <!-- Fim Cabeclaho -->

             <!-- Proximas Ofertas -->
             <section id="products">
      	       	<article id="products" class="responsive">

      	       		<!-- PRÓXIMAS OFERTAS -->
      	       		<div id="proximas-ofertas">

      	       			<div id="title-1">
      	       			    <p class="title-1">Próximas Ofertas</p>
      	       		    </div>

                          <!-- PRODUTO 1 -->
      	       			<figure id="product-1">
                              <div id="thumb"></div>
                              <div id="percent">
                              	<p class="percent">00%</p>
                              </div>
                              <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                              <a href="#" class="btn-saiba-mais">Saiba Mais</a>
      	       			</figure>

      	       			<!-- PRODUTO 2 -->
      	       			<figure id="product-2">
                              <div id="thumb"></div>
                              <div id="percent">
                              	<p class="percent">00%</p>
                              </div>
                              <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                              <a href="#" class="btn-saiba-mais">Saiba Mais</a>
      	       			</figure>

      	       			<!-- PRODUTO 3 -->
      	       			<figure id="product-3">
                              <div id="thumb"></div>
                              <div id="percent">
                              	<p class="percent">00%</p>
                              </div>
                              <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                              <a href="#" class="btn-saiba-mais">Saiba Mais</a>
      	       			</figure>

      	       			<!-- PRODUTO 4 -->
      	       			<figure id="product-4">
                              <div id="thumb"></div>
                              <div id="percent">
                              	<p class="percent">00%</p>
                              </div>
                              <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                              <a href="#" class="btn-saiba-mais">Saiba Mais</a>
      	       			</figure>

      	       		</div>

      	       		<div id="banner-publicitario-2"></div>

      	       		<div id="banner-publicitario-3"></div>

      	       		<!-- MAIS VISTAS -->
      	       		<div id="mais-vistas">

      	       			<div id="title-2">
      	       			    <p class="title-2">Mais Vistas</p>
      	       		    </div>

                          <!-- PRODUTO 1 -->
      	       			<figure id="product-1">
                              <div id="thumb"></div>
                              <div id="percent">
                              	<p class="percent">00%</p>
                              </div>
                              <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                              <a href="#" class="btn-saiba-mais">Saiba Mais</a>
      	       			</figure>

      	       			<!-- PRODUTO 2 -->
      	       			<figure id="product-2">
                              <div id="thumb"></div>
                              <div id="percent">
                              	<p class="percent">00%</p>
                              </div>
                              <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                              <a href="#" class="btn-saiba-mais">Saiba Mais</a>
      	       			</figure>

      	       			<!-- PRODUTO 3 -->
      	       			<figure id="product-3">
                              <div id="thumb"></div>
                              <div id="percent">
                              	<p class="percent">00%</p>
                              </div>
                              <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                              <a href="#" class="btn-saiba-mais">Saiba Mais</a>
      	       			</figure>

      	       			<!-- PRODUTO 4 -->
      	       			<figure id="product-4">
                              <div id="thumb"></div>
                              <div id="percent">
                              	<p class="percent">00%</p>
                              </div>
                              <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                              <a href="#" class="btn-saiba-mais">Saiba Mais</a>
      	       			</figure>

      	       		</div>

      	       		<!-- SUESTÕES PARA VOCÊ -->
      	       		<div id="sugestoes-para-voce">

      	       			<div id="title-3">
      	       			    <p class="title-3">Sugestões para você</p>
      	       		    </div>

                          <!-- PRODUTO 1 -->
      	       			<figure id="product-1">
                              <div id="thumb"></div>
                              <div id="percent">
                              	<p class="percent">00%</p>
                              </div>
                              <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                              <a href="#" class="btn-saiba-mais">Saiba Mais</a>
      	       			</figure>

      	       			<!-- PRODUTO 2 -->
      	       			<figure id="product-2">
                              <div id="thumb"></div>
                              <div id="percent">
                              	<p class="percent">00%</p>
                              </div>
                              <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                              <a href="#" class="btn-saiba-mais">Saiba Mais</a>
      	       			</figure>

      	       			<!-- PRODUTO 3 -->
      	       			<figure id="product-3">
                              <div id="thumb"></div>
                              <div id="percent">
                              	<p class="percent">00%</p>
                              </div>
                              <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                              <a href="#" class="btn-saiba-mais">Saiba Mais</a>
      	       			</figure>

      	       			<!-- PRODUTO 4 -->
      	       			<figure id="product-4">
                              <div id="thumb"></div>
                              <div id="percent">
                              	<p class="percent">00%</p>
                              </div>
                              <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                              <a href="#" class="btn-saiba-mais">Saiba Mais</a>
      	       			</figure>

      	       		</div>

      	       		<div id="banner-publicitario-4"></div>

      	       	</article>
             </section>
             <!-- Fim Proximas Ofertas -->

             <!-- Categorias -->
             <section id="categorias">
             	  <article id="categorias" class="responsive">

             	  	  <p class="categoria-title">Escolha a Categoria</p>

                    <div id="categorias-select">

                          <select name="select" class="combobox-1" id="select">
              			          <option selected="selected">Todo site</option>
              			          <option class="comboBoxText">Informática</option>
              			          <option>Laptop</option>
              			          <option>Desktops</option>
              			          <option>Monitores</option>
              			          <option>Rede</option>
              			          <option>Memórias</option>
              			          <option>Pen Drive</option>
              			          <option>Fontes</option>
              			          <option>Placa de Video</option>
              			          <option class="comboBoxText">Eletronicos</option>
              			          <option>TV</option>
              			          <option>Home Theater</option>
              			          <option>Som Automotivo</option>
              			          <option class="comboBoxText">Cine e Foto</option>
              			          <option>Camera Digital</option>
              			          <option>Filmadora</option>
              			          <option>Antenas</option>
              			          <option class="comboBoxText">Telefonia</option>
              			          <option>Celulares</option>
              			          <option>Comunicação</option>
              			          <option>Outros</option>
              		        </select>

              		        <div id="subcategorias-select">

                              <select name="select" class="combobox-2" id="select">
                              <option selected="selected">Subcategoria 1</option>
                              <option class="comboBoxText">Subcategoria 2</option>
                              <option>Subcategoria 3</option>
                              
                          </select>

            		          <a href="#" class="btn-categorias-buscar">Buscar</a>

                   </div>

             	  </article>
             </section>
             <!-- Fim Categorias -->

             <!-- Rodapé -->
             <footer id="rodape">
             	  <article id="rodape" class="responsive">

             	  	    <ul class="rodape-links-1">
             	  	 		<li><a href="#">Como Funciona</a></li>
             	  	 		<li><a href="#">Política de Privacidade</a></li>
             	  	 		<li><a href="#">Quem Somos</a></li>
             	  	 		<li><a href="#">Termos de Uso</a></li>
             	  	 	</ul>

             	  	 	<ul class="rodape-links-2">
             	  	 		<li><a href="#">Categorias / Subcategorias</a></li>
             	  	 		<li><a href="#">Cidades / Estados</a></li>
             	  	 	</ul>

             	  	 	<ul class="rodape-links-3">
             	  	 		<li><a href="#">FAQ</a></li>
             	  	 		<li><a href="#">Anuncie</a></li>
             	  	 		<li><a href="#">Fale Conosco</a></li>
             	  	 	</ul>
             	  	

             	  </article>

             	  <article id="cartoes-newsletter">

      	          <div id="cartoes-newsletter" class="responsive">

      	       	  	 <figure id="cartao">
      	       	  	 	<p class="cartao-title">Aceitamos todos os cartões de crédito e débito</p><br>
      	       	  	 	<img src="img/cartoes.jpg" class="cartoes">
      	       	  	 </figure>

      	       	  	 <figure id="certificado">
      	       	  	 	<p class="certificado-title">Certificados de Segurança</p><br>
      	       	  	 	<img src="img/certificados.jpg" class="certificado">
      	       	  	 </figure>

      	       	  	 <div id="newsletter">
      	       	  	 	<p class="newsletter-title">cadastre-se e receba novidades!</p>
      	       	  	 	<input type="text" name="nome" class="nome" placeholder="Nome:">
      	       	  	 	<input type="text" name="email" class="email" placeholder="Email:">
      	       	  	 	<a href="#" class="btn-inscrever">Inscrever</a>
      	       	  	 </div>

      	       	  </div>

             	  </article>

             	  <article id="copyright">

             	  	 <div id="copyright" class="responsive">
             	  	 	<p class="copyright-title">Classi Ofertas 2017 LTDA - Todos os direitos reservados.</p>
             	  	 </div>

             	  </article>
             </footer>
             <!-- Fim Rodapé -->

      </div>
      <!-- FIM DESKTOP VERSION -->

      <!-- MOBILE VERSION -->
      <div id="mobile-version">
          
          <!-- HEADER RESPONSIVE -->
          <header id="cabecalho-responsive">

              <!-- Login Pop Up -->
              <div id="login-pop-up">

                  <div id="form-pop-up" class="responsive">
                        <div id="pop-up-campos">
                                
                                <div id="area-cadastrado">
                                   <p class="cadastrado-title">Já é cadastrado?</p>
                                   <input type="text" name="razaosocial" class="cadastrado" placeholder="Razão social:">
                                   <input type="text" name="nomefantasia" class="cadastrado" placeholder="Nome fantasia:">
                                   <input type="text" name="cnpj" class="cadastrado" placeholder="CNPJ:">
                                   <input type="email" name="emailcad" class="cadastrado" placeholder="E-mail:">
                                   <a href="#" class="btn-cadastrado">Entrar</a>
                                </div>

                                <div id="area-primera-vez">
                                    <p class="area-primera-vez-title">Primeira vez aqui?</p>
                                    <a href="#" class="btn-area-primera-vez">Fazer Cadastro</a>
                                </div>

                            </div>
                        </div>

              </div>
              <!-- Fim Login Pop Up -->

              
              <nav id="menu-hamburger-responsive">
                  <div id="trace"></div><br>
                  <div id="trace"></div><br>
                  <div id="trace"></div>
              </nav>
              
              <figure id="logo">
                   <img src="img/logo.png" class="logo">
              </figure>
              
              <!-- CABECALHO RESPONSIVE -->
              <div id="cabecalho-responsive" class="responsive">
                  
              </div>
              <!-- FIM CABECALHO RESPONSIVE -->

              <!-- SUB MENU 1-->
              <nav id="sub-menu-1">
                <ul>
                  <li><a href="#" class="sub-menu-link">Todas as ofertas</a></li>
                  <li><a href="#" class="sub-menu-link">Ofertas em sua cidade</a></li>
                  <li><a href="#" class="sub-menu-link">Categorias</a></li>
                  <li><a href="#" class="sub-menu-link">Como funciona</a></li>
                  <li><a href="#" class="sub-menu-link">Quero anunciar</a></li>
                  <li><a href="#" class="sub-menu-link">Tire suas dúvidas</a></li>
                  <li><a href="#" class="sub-menu-link">Contato</a></li>
                </ul>
              </nav>
              <!-- FIM SUB MENU 1-->
              
          </header>
          <!-- FIM HEADER RESPONSIVE -->
          
          <!-- SLIDER RESPONSIVE -->
          <section id="slider-responsive">
              <article id="slider-responsive" class="responsive">
                  
                  <div id="block-slider">
                  </div>
                  
              </article>
          </section>
          <!-- FIM SILDER RESPONSIVE -->
          
          <!-- SEARCH RESPONSIVE -->
          <section id="search-responsive">
              <article id="search-responsive" class="responsive">
                  
                  <div id="search-form">
                      <input type="text" name="procura" class="procura" placeholder="O que procura:">
                      <input type="text" name="cidade" class="cidade" placeholder="Cidade:">
                      <a href="#" class="btn-buscar">Buscar</a>
                  </div>

                  <div id="divider"></div>
                  
                  <div id="cart-login">
                      <img src="img/cart.png" class="cart-icon">
                      <a href="#" class="btn-login">Login</a>
                  </div>
                  
              </article>
          </section>
          <!-- FIM SEARCH RESPONSIVE -->

          <!-- FPRODUCTS RESPONSIVE -->
          <section id="products-responsive">
            <article id="products-responsive" class="responsive">

                  <!-- PRÓXIMAS OFERTAS -->
                  <div id="proximas-ofertas">

                      <div id="title-1">
                          <p class="title-1">Próximas Ofertas</p>
                      </div>

                      <!-- PRODUTO 1 -->
                      <figure id="product-1">
                                <div id="thumb"></div>
                                <div id="percent">
                                  <p class="percent">00%</p>
                                </div>
                                <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                                <a href="#" class="btn-saiba-mais">Saiba Mais</a>
                      </figure>

                      <!-- PRODUTO 2 -->
                      <figure id="product-2">
                                <div id="thumb"></div>
                                <div id="percent">
                                  <p class="percent">00%</p>
                                </div>
                                <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                                <a href="#" class="btn-saiba-mais">Saiba Mais</a>
                      </figure>

                   </div>
                   <!-- FIM PRÓXIMAS OFERTAS -->

                   <div id="banner-publicitario-1"></div>

                   <!-- MAIS VISTAS -->
                   <div id="mais-vistas">

                      <div id="title-2">
                          <p class="title-2">Mais Vistas</p>
                      </div>

                      <!-- PRODUTO 1 -->
                      <figure id="product-1">
                                <div id="thumb"></div>
                                <div id="percent">
                                  <p class="percent">00%</p>
                                </div>
                                <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                                <a href="#" class="btn-saiba-mais">Saiba Mais</a>
                      </figure>

                      <!-- PRODUTO 2 -->
                      <figure id="product-2">
                                <div id="thumb"></div>
                                <div id="percent">
                                  <p class="percent">00%</p>
                                </div>
                                <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                                <a href="#" class="btn-saiba-mais">Saiba Mais</a>
                      </figure>

                   </div>
                   <!-- FIM MAIS VISTAS -->

                   <!-- SUGESTOES PARA VOCE -->
                   <div id="sugestoes-para-voce">

                      <div id="title-3">
                          <p class="title-3">Sugestões para você</p>
                      </div>

                      <!-- PRODUTO 1 -->
                      <figure id="product-1">
                                <div id="thumb"></div>
                                <div id="percent">
                                  <p class="percent">00%</p>
                                </div>
                                <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                                <a href="#" class="btn-saiba-mais">Saiba Mais</a>
                      </figure>

                      <!-- PRODUTO 2 -->
                      <figure id="product-2">
                                <div id="thumb"></div>
                                <div id="percent">
                                  <p class="percent">00%</p>
                                </div>
                                <p class="product-info">Sed ut perspiciatis<br>unde omnis</p>
                                <a href="#" class="btn-saiba-mais">Saiba Mais</a>
                      </figure>

                   </div>
                   <!-- FIM SUGESTOES PARA VOCE -->

                   <div id="banner-publicitario-2"></div>
              
            </article>
          </section>
          <!-- FIM PRODUCTS RESPONSIVE -->

          <!-- Categorias -->
             <section id="categorias">
                <article id="categorias" class="responsive">

                    <p class="categoria-title">Escolha a Categoria</p>

                    <div id="categorias-select">

                    <select name="select" class="combobox-1" id="select">
                        <option selected="selected">Todo site</option>
                        <option class="comboBoxText">Informática</option>
                        <option>Laptop</option>
                        <option>Desktops</option>
                        <option>Monitores</option>
                        <option>Rede</option>
                        <option>Memórias</option>
                        <option>Pen Drive</option>
                        <option>Fontes</option>
                        <option>Placa de Video</option>
                        <option class="comboBoxText">Eletronicos</option>
                        <option>TV</option>
                        <option>Home Theater</option>
                        <option>Som Automotivo</option>
                        <option class="comboBoxText">Cine e Foto</option>
                        <option>Camera Digital</option>
                        <option>Filmadora</option>
                        <option>Antenas</option>
                        <option class="comboBoxText">Telefonia</option>
                        <option>Celulares</option>
                        <option>Comunicação</option>
                        <option>Outros</option>
                    </select>

                    <div id="subcategorias-select">

                          <select name="select" class="combobox-2" id="select">
                              <option selected="selected">Subcategoria 1</option>
                              <option class="comboBoxText">Subcategoria 2</option>
                              <option>Subcategoria 3</option>
                              
                          </select>

                  <a href="#" class="btn-categorias-buscar">Buscar</a>

                    </div>

                </article>
             </section>
             <!-- Fim Categorias -->

             <!-- Rodapé -->
             <footer id="rodape">
                <article id="rodape" class="responsive">

                      <ul class="rodape-links-1">
                      <li><a href="#">Como Funciona</a></li>
                      <li><a href="#">Política de Privacidade</a></li>
                      <li><a href="#">Quem Somos</a></li>
                      <li><a href="#">Termos de Uso</a></li>
                    </ul>

                    <ul class="rodape-links-2">
                      <li><a href="#">Categorias / Subcategorias</a></li>
                      <li><a href="#">Cidades / Estados</a></li>
                    </ul>

                    <ul class="rodape-links-3">
                      <li><a href="#">FAQ</a></li>
                      <li><a href="#">Anuncie</a></li>
                      <li><a href="#">Fale Conosco</a></li>
                    </ul>
                  

                </article>

                <article id="cartoes-newsletter">

                  <div id="cartoes-newsletter" class="responsive">

                     <figure id="cartao">
                      <p class="cartao-title">Aceitamos todos os cartões de crédito e débito</p><br>
                      <img src="img/cartoes.jpg" class="cartoes">
                     </figure>

                     <figure id="certificado">
                      <p class="certificado-title">Certificados de Segurança</p><br>
                      <img src="img/certificados.jpg" class="certificado">
                     </figure>

                     <div id="newsletter">
                      <p class="newsletter-title">cadastre-se e receba novidades!</p>
                      <input type="text" name="nome" class="nome" placeholder="Nome:">
                      <input type="text" name="email" class="email" placeholder="Email:">
                      <a href="#" class="btn-inscrever">Inscrever</a>
                     </div>

                  </div>

                </article>

                <article id="copyright">

                   <div id="copyright" class="responsive">
                    <p class="copyright-title">Classi Ofertas 2017 LTDA - Todos os direitos reservados.</p>
                   </div>

                </article>
             </footer>
             <!-- Fim Rodapé -->
          
      </div>
      <!-- FIM MOBILE VERSION -->

       <!-- Scripts -->
       <script type="text/javascript" src="js/menus.js"></script>
       <script type="text/javascript" src="js/menu-responsive.js"></script>
       <script type="text/javascript" src="js/slider.js"></script>
       <script type="text/javascript" src="js/pop-up-login.js"></script>

	</body>
</html>

